import Head from 'next/head';
import { useState, useEffect } from 'react';
import { getSession, signOut } from 'next-auth/react';
import abi from '../../abi/bankABI.json';
import { ethers } from 'ethers';
import Link from 'next/link';

// gets a prop from getServerSideProps
function User({ user }) {
	const [currentAccount, setCurrentAccount] = useState('');
	const [ethBalance, setEthBalance] = useState(0);

	const bankContractAddress = '0x5FbDB2315678afecb367f032d93F642f64180aa3';

	useEffect(() => {
		async function getWalletBalance(address) {
			const provider = new ethers.providers.Web3Provider(window.ethereum);
			const balance = await provider.getBalance(address);
			const balanceInEth = ethers.utils.formatEther(balance);

			setEthBalance(Number(balanceInEth).toFixed(4));
		}

		if (user) {
			setCurrentAccount(user.address);
			getWalletBalance(user.address);
		}
	}, [user]);

	return (
		<div className='page-container'>
			<Head>
				<title>Smart Bank | User</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='flex flex-col rounded-xl justify-center items-center py-8 w-[80%] md:w-[70%] bg-gray-300 text-black'>
				<h1 className='mb-4'>
					Welcome to{' '}
					<span className='font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-gray-700 via-cyan-600 to-gray-700'>
						Smart Bank
					</span>
				</h1>
				<h2>
					Hello,{' '}
					{`${currentAccount.slice(0, 4)}...${currentAccount.slice(
						currentAccount.length - 4
					)}`}
				</h2>
				<p className='pt-4'>
					Current Wallet Balance:{' '}
					<span className='font-bold text-green-700'>{ethBalance}</span>
				</p>
				<div className='h-[2px] w-[80%] bg-slate-500 my-4' />
				<p className='py-5'>Which service would you like to use?</p>
				<div className='grid grid-cols-3 gap-3'>
					<button className='btn'>
						<Link href={'/deposit'}>Deposit</Link>
					</button>
					<button className='btn'>
						<Link href={'/withdraw'}>Withdraw</Link>
					</button>
					<button className='btn'>
						<Link href={'/transfer'}>Transfer</Link>
					</button>
				</div>

				{/* //!--------------------------  */}

				<button
					className='btn py-2 mt-4 bg-red-400 hover:bg-red-600 hover:text-white'
					onClick={() => signOut({ redirect: '/signin' })}
				>
					Sign out
				</button>
			</main>
		</div>
	);
}

export async function getServerSideProps(context) {
	const session = await getSession(context);

	// redirect if not authenticated
	if (!session) {
		return {
			redirect: {
				destination: '/signin',
				permanent: false,
			},
		};
	}

	return {
		props: { user: session.user },
	};
}

export default User;
