import Link from 'next/link';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import { ethers } from 'ethers';
import { getSession, signOut } from 'next-auth/react';

function Deposit({ user }) {
	const [currentAccount, setCurrentAccount] = useState('');
	const [ethBalance, setEthBalance] = useState(0);
	const [usdValue, setUsdValue] = useState(0);
	const [depositAmt, setDepositAmt] = useState(0);

	const bankContractAddress = '0x5FbDB2315678afecb367f032d93F642f64180aa3';

	const getEthInUsd = async () => {
		const response = await fetch(
			'https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD'
		);
		const data = await response.json();
		const exchangeRate = data.USD;
		return exchangeRate;
	};

	useEffect(() => {
		async function getWalletBalance(address) {
			const provider = new ethers.providers.Web3Provider(window.ethereum);
			const balance = await provider.getBalance(address);
			const balanceInEth = ethers.utils.formatEther(balance);
			const valueInUsd = await getEthInUsd();

			setEthBalance(Number(balanceInEth).toFixed(4));
			setUsdValue(valueInUsd);
		}

		if (user) {
			setCurrentAccount(user.address);
			getWalletBalance(user.address);
		}
	}, [user]);

	return (
		<div className='page-container'>
			<Head>
				<title>Smart Bank | Deposit</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='flex flex-col rounded-xl justify-center items-center py-8 w-[80%] md:w-[70%] bg-gray-200 text-black'>
				<h1 className='mb-4 font-semibold'>
					<span className='font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-gray-700 via-cyan-600 to-gray-700'>
						Smart Bank
					</span>{' '}
					Deposit
				</h1>
				<h2>
					Connected Wallet:{' '}
					<span className='text-gray-600 font-bold'>
						{`${currentAccount.slice(0, 4)}...${currentAccount.slice(
							currentAccount.length - 4
						)}`}
					</span>
				</h2>
				<p className='pt-4'>
					Current ETH Balance:{' '}
					<span className='font-bold text-green-700'>{ethBalance}</span>
				</p>
				<p className='pt-2'>
					USD Value: $
					<span className='font-bold text-green-700'>{usdValue}</span>
				</p>
				<div className='h-[2px] w-[80%] bg-slate-500 my-4' />
				<div className='mb-4'>
					<label htmlFor='depositAmount'>
						Deposit ETH Amount:
						<input
							type='number'
							className='bg-white rounded-md ml-2'
							value={depositAmt}
							onChange={e => setDepositAmt(e.target.value)}
						/>
					</label>
				</div>
				<div className='grid grid-cols-2 gap-4'>
					<button className='btn hover:bg-gradient-to-br from-gray-700 via-cyan-600 to-gray-700'>
						<Link href={'/user'}>Back</Link>
					</button>
					<button className='btn'>Make Deposit</button>
				</div>
			</main>
		</div>
	);
}

export async function getServerSideProps(context) {
	const session = await getSession(context);

	// redirect if not authenticated
	if (!session) {
		return {
			redirect: {
				destination: '/signin',
				permanent: false,
			},
		};
	}

	return {
		props: { user: session.user },
	};
}
export default Deposit;
