import Head from 'next/head';
import Image from 'next/image';
import { useState, useEffect } from 'react';
import abi from '../abi/bankABI.json';
import { ethers } from 'ethers';
import Link from 'next/link';

export default function Home() {
	const [currentAccount, setCurrentAccount] = useState('');
	const [ethBalance, setEthBalance] = useState(0);

	const bankContractAddress = '0x5FbDB2315678afecb367f032d93F642f64180aa3';

	// Wallet connection logic
	const isWalletConnected = async () => {
		try {
			const { ethereum } = window;

			const accounts = await ethereum.request({ method: 'eth_accounts' });

			if (accounts.length > 0) {
				const account = accounts[0];

				setCurrentAccount(account);

				console.log('wallet is connected! ' + account);
			} else {
				setCurrentAccount('');
				console.log('make sure MetaMask is connected');
			}
		} catch (error) {
			console.log('error: ', error);
		}
	};

	const connectWallet = async () => {
		try {
			const { ethereum } = window;

			if (!ethereum) {
				console.log('please install MetaMask');
			}

			const accounts = await ethereum.request({
				method: 'eth_requestAccounts',
			});

			setCurrentAccount(accounts[0]);
		} catch (error) {
			console.log(error);
		}
	};

	useEffect(() => {
		async function getWalletBalance(address) {
			const provider = new ethers.providers.Web3Provider(window.ethereum);
			const balance = await provider.getBalance(address);
			const balanceInEth = ethers.utils.formatEther(balance);

			setEthBalance(Number(balanceInEth).toFixed(4));
		}

		isWalletConnected();

		if (currentAccount) {
			getWalletBalance(currentAccount);
		}
	}, [currentAccount]);

	return (
		<div className='page-container'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='flex flex-col rounded-xl justify-center items-center py-8 w-[80%] md:w-[70%] bg-gray-300 text-black'>
				<h1 className='mb-4'>Welcome to Cold Bank</h1>
				{!currentAccount ? (
					<>
						<p>
							Please log in with your Metamask account to begin using our
							services
						</p>
						<button className='btn' onClick={connectWallet}>
							log in{' '}
						</button>
					</>
				) : (
					<>
						<h2>
							Hello,{' '}
							{`${currentAccount.slice(0, 4)}...${currentAccount.slice(
								currentAccount.length - 4
							)}`}
						</h2>
						<p className='pt-4'>
							Current Wallet Balance:{' '}
							<span className='font-bold text-green-700'>{ethBalance}</span>
						</p>
						<div className='h-[2px] w-[80%] bg-slate-500 my-4' />
						<p className='py-5'>Which service would you like to use?</p>
						<div className='grid grid-cols-3 gap-3'>
							<button className='btn'>
								<Link href={'/deposit'}>Deposit</Link>
							</button>
							<button className='btn'>
								<Link href={'/withdraw'}>Withdraw</Link>
							</button>
							<button className='btn'>
								<Link href={'/transfer'}>Transfer</Link>
							</button>
						</div>
					</>
				)}
			</main>
		</div>
	);
}
